services:
  app:
    build: .
    command: locust -f locustfile.py --host=${LOCUST_TARGET}
    ports:
      - "8089:8089"
    depends_on:
      - dimmentor_psql
    volumes:
      - .:/app
    environment:
      - LOCUST_TARGET=http://dimmentor_psql:5432

  dimmentor_psql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dimmentor_wallets
      - POSTGRES_USER=dimmentor
      - POSTGRES_PASSWORD=Dimalong1910+
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: