services:
  app:
    build: .
    command: locust -f locustfile.py
    ports:
      - "8089:8089"
    depends_on:
      - walletapp
  walletapp:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dimmentor_wallets
      - POSTGRES_USER=dimmentor
      - POSTGRES_PASSWORD=Dimalong1910+
    ports:
      - "5432:5432"